- name: Install docker
  become: true
  apt:
    name: docker.io
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes

- name: Create Docker config directory
  become: true
  file:
    path: /etc/docker/
    state: directory
    mode: '0755'

- name: Configure Docker
  become: true
  copy:
    #"exec-opts": ["native.cgroupdriver=systemd"],
    #"log-driver": "journald",
    #"storage-driver": "overlay2"
    content: |
    #  {
    #    "log-driver": "journald"
    #  }
    dest: /etc/docker/daemon.json
  register: docker_conf

- name: Start Docker
  become: true
  systemd:
    name: docker
    daemon_reload: yes
    state: "{{ 'reloaded' if docker_conf.changed else 'started' }}"
    enabled: true
